project 'SpyApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpyApp

  target 'SpyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
